server:
  port: ${PORT:4899}

#base-url: /api

spring:
  application:
    name: collectorApp

  profiles:
    active: ${APP_ENV:dev}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: none


  mvc:
    hiddenmethod:
      filter:
        enabled: true

bot:
  botToken: 1114352987:AAG8IzQuuMd8qIzEbcNEuaZFqQX5ifsEBI0
  botUserName: football_statistic_bot
  botHookPath: https://b57e-178-72-76-194.ngrok.io